Create release.yml CI process
Signed-off-by: Derek Nola <derek.nola@suse.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -66,11 +66,75 @@ jobs:
             VERSION=${{ github.ref_name }}
             DRONE_TAG=${{ github.ref_name }}
 
-  create-release-assets:
+  upload-release-airgap:
+    name: Build Airgap Package for ${{ matrix.arch }}
+    runs-on: ubuntu-latest # Runs on standard runner, docker pulls with --platform
+    permissions: 
+      contents: write # Needed to update release with assets
+    strategy:
+      matrix:
+        arch: [amd64, arm64, arm] # Add other architectures if needed
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Install Dependencies
+        run: sudo apt-get update -y && sudo apt-get install -y zstd pigz
+
+      - name: Create Airgap Package (${{ matrix.arch }})
+        env:
+          # Set ARCH based on matrix value for use in filenames
+          ARCH: ${{ matrix.arch }}
+          OUTPUT_DIR: ./dist/artifacts
+          PLATFORM: ${{ matrix.arch == 'arm' && 'linux/arm/v7' || format('linux/{0}', matrix.arch) }}
+        
+        run: |
+          mkdir -p ${OUTPUT_DIR}
+          airgap_image_file='scripts/airgap/image-list.txt'
+          if [ ! -f "$airgap_image_file" ]; then
+            echo "Airgap image list not found at $airgap_image_file"
+            exit 1
+          fi
+          images=$(cat "${airgap_image_file}")
+
+          images=$(cat "${airgap_image_file}")
+          xargs -n1 docker pull --platform $PLATFORM <<< "${images}"
+
+          echo "Saving images to tarball..."
+          docker save ${images} -o ${OUTPUT_DIR}/k3s-airgap-images-${ARCH}.tar
+
+          echo "Compressing tarball with zstd..."
+          zstd --no-progress -T0 -f -16 --long=25 ${OUTPUT_DIR}/k3s-airgap-images-${ARCH}.tar -o ${OUTPUT_DIR}/k3s-airgap-images-${ARCH}.tar.zst
+
+          echo "Compressing tarball with pigz..."
+          pigz -v -c ${OUTPUT_DIR}/k3s-airgap-images-${ARCH}.tar > ${OUTPUT_DIR}/k3s-airgap-images-${ARCH}.tar.gz
+
+          if [ "${ARCH}" = "amd64" ]; then
+            cp "${airgap_image_file}" ${OUTPUT_DIR}/k3s-images.txt
+          fi
+
+      - name: Upload Assets to Release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: |
+            dist/artifacts/k3s-airgap-images*
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  upload-release-assets:
     name: Prepare and Upload Release Assets
+    permissions: 
+      contents: write # Needed to update release with assets
     runs-on: ubuntu-latest
     needs: [build-binary-amd64, build-binary-arm64]
     steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
     - name: "Download Binaries"
       uses: actions/download-artifact@v4
       with:
@@ -78,17 +142,24 @@ jobs:
         path: ./dist/artifacts
         merge-multiple: true
 
-    - name: Append sha256sum files
+    - name: Format sha256sum files
       run: |
         for file in ./dist/artifacts/*.sha256sum; do
-          mv "$file" "${file}.txt"
+          filename=$(basename "$file")
+          if [[ "$filename" == *"-arm64.sha256sum" ]]; then
+            mv "$file" "./dist/artifacts/sha256sum-arm64.txt"
+          elif [[ "$filename" == *"-arm.sha256sum" ]]; then
+            mv "$file" "./dist/artifacts/sha256sum-armhf.txt"
+          else
+            mv "$file" "./dist/artifacts/sha256sum-amd64.txt"
+          fi
         done
     
     - name: Upload Assets to Release
       uses: softprops/action-gh-release@v2
       with:
         files: |
-          dist/artifacts/k3s-*
-          dist/artifacts/sha256sun*
+          dist/artifacts/k3s*
+          dist/artifacts/sha256sum*
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
